DataStructures.Console.Implementation.SortImplementation.DisplaySelectionSortResult();
DataStructures.Console.Implementation.SortImplementation.DisplayBubbleSortResult();
DataStructures.Console.Implementation.SortImplementation.DisplayMergeSortResult();
