DataStructures.Console.Implementation.SearchImplementation.DisplayLinearSearchResult();
DataStructures.Console.Implementation.SearchImplementation.DisplayBinarySearchResult();
DataStructures.Console.Implementation.SearchImplementation.DisplayBinarySearchRecursiveResult();
